In [1]:
from __future__ import print_function
import torch

In [6]:
torch.empty(5,3)

tensor([[-1.1097e-12,  4.5787e-41, -1.1097e-12],
        [ 4.5787e-41,  5.1017e-11,  1.3563e-19],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  6.1530e-39,  3.2933e-18],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [8]:
torch.rand(5,3)

tensor([[0.2347, 0.6189, 0.1220],
        [0.6175, 0.7728, 0.5246],
        [0.8728, 0.6166, 0.0759],
        [0.3347, 0.6231, 0.1640],
        [0.6629, 0.9553, 0.2567]])

In [9]:
torch.zeros(5, 3, dtype=torch.long)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [12]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [13]:
# create a new tensor based on an existing tensor
x.new_ones(5, 3, dtype=torch.double)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [15]:
torch.randn_like(x, dtype=torch.float) #override the dtype
# note that the result is the same size

tensor([ 0.3805, -0.5431])

In [21]:
x.shape

torch.Size([2])

In [26]:
x = torch.rand(5,3)
y = torch.rand(5, 3)
print(x + y)
print(torch.add(x,y))
print((x + y) == torch.add(x,y))

tensor([[0.6701, 0.6825, 1.5674],
        [1.0905, 1.5901, 0.9702],
        [1.1975, 0.5845, 1.1259],
        [0.9146, 0.7658, 0.7740],
        [0.9205, 0.9333, 0.5675]])
tensor([[0.6701, 0.6825, 1.5674],
        [1.0905, 1.5901, 0.9702],
        [1.1975, 0.5845, 1.1259],
        [0.9146, 0.7658, 0.7740],
        [0.9205, 0.9333, 0.5675]])
tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.uint8)


In [27]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[0.6701, 0.6825, 1.5674],
        [1.0905, 1.5901, 0.9702],
        [1.1975, 0.5845, 1.1259],
        [0.9146, 0.7658, 0.7740],
        [0.9205, 0.9333, 0.5675]])


In [28]:
# in place addition
# adds x to y
y.add_(x)
print(y)

tensor([[0.6701, 0.6825, 1.5674],
        [1.0905, 1.5901, 0.9702],
        [1.1975, 0.5845, 1.1259],
        [0.9146, 0.7658, 0.7740],
        [0.9205, 0.9333, 0.5675]])


In [29]:
# standard indexing
print(x[:, 1])

tensor([0.4250, 0.7148, 0.4152, 0.0578, 0.7907])


In [30]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [31]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.0563])
0.056332413107156754


In [32]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([1.0563], device='cuda:0')
tensor([1.0563], dtype=torch.float64)


## Autograd

In [33]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [34]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [35]:
print(y.grad_fn)

In [36]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward1>)


In [38]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))

print(a.requires_grad)
a.requires_grad_(True)

print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [39]:
out.backward()

In [40]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [41]:
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([1144.0500, 1166.5734, -479.4627], grad_fn=<MulBackward0>)


In [42]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


In [43]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False
